HEALTH_CHECK_SUCCESS = 'API is active and running'
ACCOUNT_NOT_FOUND = 'Account not found'
PRODUCT_NOT_FOUND = 'Product not found'
PRODUCTS_FETCH_SUCCESS = 'Products fetched successfully'
ACCOUNT_SCORE_FETCH_SUCCESS = 'Account score fetched successfully'
SUCCESS_STATUS = 'SUCCESS'
ERROR_STATUS = 'ERROR'